theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: This is the Title of the Site
description: Site Description
show_downloads: True
linkedin: "https://www.linkedin.com/in/ivan-lee-c"
